name: Lint and Format and Test

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - main

jobs:
  lint:
    name: Lint and format
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
          cache: pip

      - name: ğŸ“¦ Install Modules
        run: pip install -r requirements.txt

      - name: âš¡ï¸ Run linting check
        run: black .

      - name: âš«ï¸ Run formatting check
        run: ruff .

      - name: ğŸ¤– Run Tests
        run: pytest
